name: "some node"
desc: "because i saID SO"
event: idk
edges:
  "The bedroom door to Michael's room":
    weight: 2
    endpointFilename: michaelnotbeinggay
    condition: imnotgay
  "Closet door":
    endpointFilename: michaelnotbeinggay

